# Generated by Django 6.0.2 on 2026-02-20 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='Oracle', max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=1521)),
                ('service_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password_encrypted', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oracle_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
